name: Prod Build and Deploy to ArgoCD

on:
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        pytest tests/    # Replace with your test framework and directory

    - name: Build and push Polybot image to DockerHub
      run: |
        cd polybot
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my_yolo5_k8s:v2
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

#    - name: Build Docker image
#      if: success()
#      run: |
#        docker build -t your-docker-repo/polybot_prod:latest .
#        docker push your-docker-repo/polybot_prod:latest

    - name: Deploy to Prod using ArgoCD
      if: success()
      run: |
        argocd app sync polybot-prod --prune --force
